services:
  # RabbitMQ - Message Broker cho Celery
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_ERLANG_COOKIE: "mycookie"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  # Redis - Cache & Celery Result Backend
  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL - Database của UserService
  user-db:
    image: postgres:latest
    container_name: user-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user_postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django User Service
  user-service:
    build: ./backend/UserService
    container_name: user-service
    restart: always
    volumes:
      - ./backend/UserService:/UserService
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Worker - Xử lý các Task từ RabbitMQ
  celery-worker:
    build: ./backend/UserService
    container_name: celery-worker
    restart: always
    volumes:
      - ./backend/UserService:/UserService
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A UserService worker --loglevel=info

  # Celery Beat - Lên lịch Task tự động
  user-celery-beat:
    build: ./backend/UserService
    container_name: user-celery-beat
    restart: always
    volumes:
      - ./backend/UserService:/UserService
    env_file:
      - .env
    depends_on:
      user-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A UserService beat --loglevel=info

volumes:
  postgres_user_data:
