# Generated by Django 5.1.4 on 2025-02-06 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0008_alter_otp_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='note',
            field=models.CharField(choices=[('register', 'Register'), ('change_password', 'Change Password'), ('change_email', 'Change Email'), ('change_phone_number', 'Change Phone Number')], default='register', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 11, 8, 47, 907129, tzinfo=datetime.timezone.utc)),
        ),
    ]
