# Generated by Django 5.1.4 on 2025-02-07 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPI', '0009_otp_note_alter_otp_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp_try',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 8, 43, 38, 155488, tzinfo=datetime.timezone.utc)),
        ),
    ]
